import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { useContent, getContent, getLink } from "../../utils";
import { isMobile } from "react-device-detect";
import HeaderMobile from "../../components/HeaderMobile";
import HomeMenuMobile from "../../components/HomeMenuMobile";

export default function Course() {
  const router = useRouter();
  const { lang, active } = router.query;
  const content = useContent();
  const [course, setCourse] = useState(null);
  const [activeP, setActiveP] = useState(null);
  const [menuOpen, setMenuopen] = useState(false);
  const [mobile, setMobile] = useState(false);

  useEffect(() => {
    setCourse(lang === "it" ? "aci" : "bei");
  }, [lang]);

  useEffect(() => {
    setActiveP(active);
  }, [active]);

  useEffect(() => {
    setMobile(isMobile);
  }, [isMobile]);

  return (
    <div>
      <Head>
        <title>ACI BEI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full md:h-screen overflow-hidden">
        {mobile && <HeaderMobile setMenuopen={setMenuopen} />}
        {mobile && menuOpen && (
          <HomeMenuMobile
            course={course}
            lang={lang}
            setMenuopen={setMenuopen}
          />
        )}
        <div className="w-full h-full grid grid-cols-1 md:grid-cols-2">
          <div className="md:h-screen relative pl-4 md:pl-16 pt-4 md:pt-16">
            <div className="h-full flex flex-col justify-between">
              <div className="flex flex-col">
                <Link passHref href={`/${lang}/course?active=1`}>
                  <div
                    className={`${
                      activeP === "1" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue my-1 md:my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_1_1`)}
                  </div>
                </Link>
                <Link passHref href={`/${lang}/course?active=2`}>
                  <div
                    className={`${
                      activeP === "2" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue my-1 md:my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_1_2`)}
                  </div>
                </Link>
                <a
                  target="_blank"
                  rel="noreferrer"
                  href={getLink(content, `${course}_menu_1_3`)}
                  className="hover:no-underline	"
                >
                  <div
                    className={`${
                      activeP === "3" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue my-1 md:my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_1_3`)}
                  </div>
                </a>
                <a
                  target="_blank"
                  rel="noreferrer"
                  href={getLink(content, `${course}_menu_1_4`)}
                  className="hover:no-underline	"
                >
                  <div
                    className={`${
                      activeP === "4" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue my-1 md:my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_1_4`)}
                  </div>
                </a>
                <a
                  target="_blank"
                  rel="noreferrer"
                  href={getLink(content, `${course}_menu_1_5`)}
                  className="hover:no-underline	"
                >
                  <div
                    className={`${
                      activeP === "5" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue my-1 md:my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_1_5`)}
                  </div>
                </a>
              </div>
              <div className="flex flex-col pb-8">
                <Link passHref href={`/${lang}/home`}>
                  <div className="border-4 border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue hover:bg-blue hover:text-gray my-1 md:my-2 cursor-pointer">
                    Home
                  </div>
                </Link>
              </div>
            </div>
          </div>
          <div className="relative pl-4 md:pl-0 pr-4 md:pr-16 pt-8 md:pt-16 overflow-y-scroll">
            <div className="h-4 w-full bg-blue mb-8"></div>
            <div
              className="text-blue my-2 text-xl md:text-2xl leading-normal	"
              dangerouslySetInnerHTML={{
                __html: getContent(
                  content,
                  `${course}_course_content_${active}`
                ),
              }}
            ></div>
          </div>
        </div>
      </main>
    </div>
  );
}
