import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { useContent, getContent, getLink } from "../../utils";
import Slider from "react-slick";
import { isMobile } from "react-device-detect";
import HeaderMobile from "../../components/HeaderMobile";
import HomeMenuMobile from "../../components/HomeMenuMobile";

export default function Minds() {
  const router = useRouter();
  const { lang, active } = router.query;
  const content = useContent();
  const [course, setCourse] = useState(null);
  const [activeP, setActiveP] = useState(null);
  const [menuOpen, setMenuopen] = useState(false);
  const [mobile, setMobile] = useState(false);

  useEffect(() => {
    setCourse(lang === "it" ? "aci" : "bei");
  }, [lang]);

  useEffect(() => {
    setActiveP(active);
  }, [active]);

  useEffect(() => {
    setMobile(isMobile);
  }, [isMobile]);

  const settings = {
    dots: false,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  const gallery1 = getContent(content, `minds_gallery_1`).split(",");
  const gallery2 = getContent(content, `minds_gallery_2`).split(",");
  const gallery3 = getContent(content, `minds_gallery_3`).split(",");

  return (
    <div>
      <Head>
        <title>ACI BEI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full md:h-screen overflow-hidden">
        {mobile && <HeaderMobile setMenuopen={setMenuopen} />}
        {mobile && menuOpen && (
          <HomeMenuMobile
            course={course}
            lang={lang}
            setMenuopen={setMenuopen}
          />
        )}
        <div className="w-full h-full grid grid-cols-1 md:grid-cols-2">
          <div className="h-screen relative pl-4 md:pl-16 pt-4 md:pt-16">
            <div className="h-full flex flex-col justify-between">
              <div className="flex flex-col">
                <Link passHref href={`/${lang}/minds?active=1`}>
                  <div
                    className={`${
                      activeP === "1" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-2 px-4 w-fit text-xl font-bold text-blue my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_3_1`)}
                  </div>
                </Link>
                <Link passHref href={`/${lang}/minds?active=2`}>
                  <div
                    className={`${
                      activeP === "2" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-2 px-4 w-fit text-xl font-bold text-blue my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_3_2`)}
                  </div>
                </Link>
                <Link passHref href={`/${lang}/minds?active=3`}>
                  <div
                    className={`${
                      activeP === "3" ? "border-8" : "border-4"
                    } border-blue hover:bg-blue hover:text-gray py-2 px-4 w-fit text-xl font-bold text-blue my-2 cursor-pointer`}
                  >
                    {getContent(content, `${course}_menu_3_3`)}
                  </div>
                </Link>
              </div>
              <div className="flex flex-col pb-8">
                <Link passHref href={`/${lang}/home`}>
                  <div className="border-4 border-blue hover:bg-blue hover:text-gray py-2 px-4 w-fit text-xl font-bold text-blue hover:bg-blue hover:text-gray my-2 cursor-pointer">
                    Home
                  </div>
                </Link>
              </div>
            </div>
          </div>
          <div className="relative pl-4 md:pl-0 pr-4 md:pr-16 pt-16 overflow-y-scroll">
            <div className="h-4 w-full bg-red mb-8"></div>
            <div
              className="text-blue my-2 pb-4 text-2xl "
              dangerouslySetInnerHTML={{
                __html: getContent(
                  content,
                  `${course}_minds_content_${active}`
                ),
              }}
            ></div>
            {activeP === "1" && (
              <div>
                <div className="p-6">
                  <Slider {...settings}>
                    {gallery1.map((v, i) => {
                      return (
                        <div key={`gallery-1-${v}`}>
                          <img
                            src={`/gallery/minds2021/${v}`}
                            style={{ height: "400px", margin: "0 auto" }}
                            alt={`Gallery image ${i} - MINDS`}
                          />
                        </div>
                      );
                    })}
                  </Slider>
                </div>
                <div className="p-6">
                  <Slider {...settings}>
                    {gallery2.map((v, i) => {
                      return (
                        <div key={`gallery-2-${v}`}>
                          <img
                            src={`/gallery/minds2022/${v}`}
                            style={{ height: "400px", margin: "0 auto" }}
                            alt={`Gallery image ${i} - MINDS`}
                          />
                        </div>
                      );
                    })}
                  </Slider>
                </div>
                <div className="p-6">
                  <Slider {...settings}>
                    {gallery3.map((v, i) => {
                      return (
                        <div key={`gallery-3-${v}`}>
                          <img
                            src={`/gallery/minds2023/${v}`}
                            style={{ height: "400px", margin: "0 auto" }}
                            alt={`Gallery image ${i} - MINDS`}
                          />
                        </div>
                      );
                    })}
                  </Slider>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
