import Head from "next/head";
import { useEffect, useState } from "react";
import { useContent } from "../../utils";
import { useRouter } from "next/router";
import { isMobile } from "react-device-detect";
import HeaderMobile from "../../components/HeaderMobile";
import HomeMenuMobile from "../../components/HomeMenuMobile";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  const { lang } = router.query;
  const content = useContent();
  const [mobile, setMobile] = useState(false);
  const [menuOpen, setMenuopen] = useState(false);
  const [course, setCourse] = useState(null);

  useEffect(() => {
    setCourse(lang === "it" ? "aci" : "bei");
  }, [lang]);

  useEffect(() => {
    setMobile(isMobile);
  }, [isMobile]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mobile && <HeaderMobile setMenuopen={setMenuopen} />}
      {mobile && menuOpen && (
        <HomeMenuMobile course={course} lang={lang} setMenuopen={setMenuopen} />
      )}
      <main className="w-full">
        <div className="w-full flex flex-col md:flex-row items-center p-4 md:p-16 md:pb-0 h-screen">
          <div className="w-full md:w-[40vw] md:h-full">
            <div className="flex h-full items-end">
              <div className="flex flex-col pb-8">
                <Link passHref href={`/${lang}/home`}>
                  <div className="border-4 border-blue hover:bg-blue hover:text-gray py-0 md:py-2 px-2 md:px-4 w-fit text-md md:text-xl font-bold text-blue hover:bg-blue hover:text-gray my-1 md:my-2 cursor-pointer">
                    Home
                  </div>
                </Link>
              </div>
            </div>
          </div>
          <div className="w-full md:w-[60vw] h-screen overflow-y-auto pb-4 md:pb-16">
            <div className="text-blue text-xl">
              <div className="font-bold py-4">
                INFORMATIVA E DICHIARAZIONE DI CONSENSO AL TRATTAMENTO DEI DATI
                PERSONALI AI SENSI DEGLI ART. 13 e 14 DEL REGOLAMENTO UE N.
                679/2016 DEL 27 APRILE 2016{" "}
              </div>
              La vigente informativa viene rilasciata ai sensi dell’art. 13 e 14
              del Regolamento UE 2016/679 del 27 aprile 2016 relativo alla
              protezione delle persone fisiche con riguardo al trattamento dei
              dati personali e nel rispetto della normativa in materia di
              trattamento dei dati personali, nonché alla libera circolazione di
              tali dati.
              <br />
              Questa informativa si riferisce al sito
              https://www.architettura-aaci.polimi.it, tramite il quale si offre
              una presentazione del corso di Laurea magistrale ACI/BEI (ita/eng)
              della scuola AUIC del Politecnico di Milano. La presente policy
              sulla privacy è resa solo per il sito Architettura Aaci e fornisce
              informazioni a coloro che interagiscono col sito, accessibile per
              via telematica e afferente al dominio:
              https://www.architettura-aaci.polimi.it.{" "}
              <div className="font-bold py-4">
                Titolare del trattamento dati
              </div>{" "}
              Politecnico di Milano – Direttore Generale su delega del Rettore
              pro-tempore - contatto: dirgen@polimi.it <br /> Responsabile
              interno del trattamento … Dati di contatto: …
              <div className="font-bold py-4">
                Responsabile protezione dati e punti di contatto
              </div>{" "}
              privacy@polimi.it tel.: 0223999378
              {/*<div className="font-bold py-4">
              Finalità del trattamento, base giuridica, categorie di dati e
              periodo di conservazione
            </div>{" "}
            Ai fini dell’applicazione della normativa europea e nazionale in
            materia (Reg. UE 679/2016, d’ora in poi Regolamento), si informa che
            i dati suoi dati personali saranno utilizzati per le seguenti
            finalità: Finalità del trattamento cui sono destinati i dati
            personali Base giuridica del trattamento Categorie di dati personali
            oggetto di trattamento Periodo di conservazione dei dati personali
            Finalità 1 Attività di comunicazione istituzionale del Dipartimento
            Interesse pubblico (art. 6, comma 1, lett. e) del Regolamento UE).
           <br />
            <li>Dati identificativi </li>
            <li>Dati di contatto </li>
            <li>
              … … Finalità 2 Compilazione di Form online Interesse pubblico
              (art. 6, comma 1, lett. e) del Regolamento UE).{" "}
            </li>
            <li>Dati identificativi </li>
            <li>
              Dati di contatto … Finalità 3 Manutenzione e monitoraggio della
              piattaforma online, relativamente alla gestione tecnica e
              sistemistica dei dati e alla struttura hardware Interesse pubblico
              (art. 6, comma 1, lett. e) del Regolamento UE).{" "}
            </li>
            <li>Dati identificativi </li>
            <li>
              Dati di contatto … Finalità 4 Finalità statistiche, di
              conservazione e archiviazione Interesse pubblico (art. 6, comma 1,
              lett. e) del Regolamento UE).{" "}
            </li>
            <li>Dati identificativi </li>
            <li>Dati di contatto … </li> */}
              <div className="font-bold py-4">Natura dei dati</div> Il
              conferimento dei dati è facoltativo Il rifiuto a fornire i dati
              comporta l&#39;impossibilità di eseguire le finalità previste.{" "}
              <div className="font-bold py-4">Modalità di trattamento</div> Il
              trattamento per le finalità sopra indicate è effettuato su
              supporto digitale, manualmente e/o con strumenti elettronici o,
              comunque, automatizzati. L’accesso ai dati acquisiti per le
              suddette finalità è consentito al personale debitamente
              autorizzato.{" "}
              <div className="font-bold py-4">Categorie di destinatari</div> In
              relazione alle finalità indicate i dati potranno essere comunicati
              ai seguenti soggetti pubblici e/o privati:{" "}
              <li> Eventuali fornitori o responsabili del trattamento</li>
              <div className="font-bold py-4">
                Trasferimento a Paesi extra-UE o Organizzazioni internazionali
              </div>{" "}
              I dati personali non saranno in alcun modo trasferiti in Paesi
              extra-UE o Organizzazioni internazionali. Diritti degli
              interessati In qualità di soggetto interessato può chiedere in
              qualsiasi momento al Titolare:{" "}
              <li>
                {" "}
                la conferma dell’esistenza o meno di dati personali che la
                riguardano;{" "}
              </li>
              <li>
                {" "}
                l&#39;accesso ai suoi dati personali ed alle informazioni
                relative agli stessi;{" "}
              </li>
              <li>
                {" "}
                la rettifica dei dati inesatti o l&#39;integrazione di quelli
                incompleti;{" "}
              </li>
              <li>
                {" "}
                la cancellazione dei dati personali che la riguardano (al
                verificarsi di una delle condizioni indicate nell&#39;art. 17,
                paragrafo 1 del Regolamento e nel rispetto delle eccezioni
                previste nel paragrafo 3 dello stesso articolo);{" "}
              </li>
              <li>
                {" "}
                la limitazione del trattamento dei suoi dati personali (al
                ricorrere di una delle ipotesi indicate nell&#39;art. 18,
                paragrafo 1 del Regolamento), la trasformazione in forma anonima
                o il blocco dei dati trattati in violazione di legge, compresi
                quelli di cui non è necessaria la conservazione in relazione
                agli scopi per i quali i dati sono stati raccolti o
                successivamente trattati. In qualità di soggetto interessato ha
                inoltre diritto di opporsi in tutto o in parte:{" "}
              </li>
              <li>
                {" "}
                per motivi legittimi al trattamento dei dati personali che la
                riguardano, ancorché pertinenti allo scopo della raccolta;{" "}
              </li>
              <li>
                {" "}
                al trattamento di dati personali che la riguardano per l’invio
                di comunicazioni atte a promuovere iniziative formative ed
                eventi del Politecnico di Milano.
              </li>
              <br /> Tali diritti sono esercitabili rivolgendosi a
              privacy@polimi.it. Qualora ritenga che i suoi diritti siano stati
              violati dal titolare e/o da un terzo, ha il diritto di proporre
              reclamo all’Autorità per la protezione dei dati personali e/o ad
              altra autorità di controllo competente in forza del Regolamento.
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
