import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Teachings() {
  const router = useRouter();
  const { lang } = router.query;

  return (
    <div>
      <Head>
        <title>ACI BEI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen">
        <div className="w-full grid grid-cols-2">
          <div className="relative pl-16 pt-16">
            <div className="flex flex-col">
              <div className="flex flex-col">
                <div className="relative">
                  <div className="border-4 border-blue p-4 w-fit text-lg font-bold text-blue my-2 ">
                    CORSO DI STUDI
                  </div>
                  <div className="border-4 flex-col flex border-blue border-dashed top-0 p-4 w-fit text-lg font-bold text-blue my-2 absolute left-64">
                    <Link href={""}>
                      <div>organigramma</div>
                    </Link>
                    <Link href={""}>
                      <div>contatti</div>
                    </Link>
                    <Link href={""}>
                      <div>regolamento</div>
                    </Link>
                    <Link href={""}>
                      <div>Scheda SUA e riesame</div>
                    </Link>
                  </div>
                </div>
                <div className="border-4 border-blue p-4 w-fit text-lg font-bold text-blue my-2 ">
                  INSEGNAMENTI
                </div>
                <div className="border-4 border-blue p-4 w-fit text-lg font-bold text-blue my-2 ">
                  MInDS
                </div>
                <div className="border-4 border-blue p-4 w-fit text-lg font-bold text-blue my-2 ">
                  ALTRE OPPORTUNITÀ
                </div>
                <div className="border-4 border-blue p-4 w-fit text-lg font-bold text-blue my-2 ">
                  TESI DI LAUREA
                </div>
              </div>
              <p className="text-blue text-xl">Lorem ipsum dolorem sit amet</p>
            </div>
          </div>
          <div className="relative "></div>
        </div>
      </main>
    </div>
  );
}
