import Head from "next/head";
import Link from "next/link";
import { useContent } from "./utils";

export default function Home() {
  const content = useContent();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <div className="w-full flex flex-col items-center">
          <div className="text-blue text-2xl pt-8 h-[10vh] flex items-center justify-center">
            Politecnico di Milano Scuola di Architettura Urbanistica Ingegneria
            delle Costruzioni
          </div>
          <div className="relative p-16 w-full h-[80vh] flex items-center justify-center">
            <Link href={"/it/home"}>
              <div className="cursor-pointer font-bold text-9xl hover:bg-blue hover:text-gray w-96 h-96  text-blue border-blue border-16 rounded-full flex justify-center items-center absolute right-[48%]">
                ACI
              </div>
            </Link>

            <Link href={"/en/home"}>
              <div className="cursor-pointer font-bold text-9xl hover:bg-blue hover:text-gray w-96 h-96  text-blue border-blue border-16 rounded-full flex justify-center items-center absolute left-[48%]">
                BEI
              </div>
            </Link>
          </div>
          <div className="text-blue text-2xl h-[10vh] flex items-center justify-center">
            Corso di Laurea Magistrale Architettura Ambiente Costruito Interni
            // Architecture Built Environment Interiors
          </div>
        </div>
      </main>
    </div>
  );
}
